name: Black Format Check

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black==25.1.0

      - name: Check formatting with Black
        run: black --check --line-length 120 --required-version 25.1.0 --target-version py38 --target-version py39 .