name: Flake8 Unused Imports and Variables Check

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  flake8-unused:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install and run flake8
        run: |
          pip install flake8
          python -m flake8 --select=F401,F841 --show-source .