name: Secrets & Credentials Scan

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # <-- Add this line to fetch full history

      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}